openapi: 3.0.0
info:
  title: Digit-Ai Zapier Proxy
  version: 1.0.0
  description: Forwards lead data to Zapier via a Vercel proxy
servers:
  - url: https://vercel.com/adsangler1/api
paths:
  /send-lead:
    post:
      summary: Send lead capture data to Zapier
      operationId: sendLeadData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lead'
      responses:
        '200':
          description: Successfully forwarded to Zapier
components:
  schemas:
    Lead:
      type: object
      properties:
        email:
          type: string
        full_name:
          type: string
        company_name:
          type: string
        score:
          type: integer
        max_score:
          type: integer
        version:
          type: string
        timestamp:
          type: string
      required:
        - email
        - full_name
        - company_name
